### ISSUE TITLE
Changing the default src fallback to be a different size

### ISSUE THREAD

**Issue by guyhamilton** [goiblas/gulp-add-source-picture#1]
Hi, great plugin! I was just wondering whether there is a way to make the default img fallback is say the @3x version? Because when I set the default fallback as say the 3x version, the result is only the array of images part of the @3x size, not all the other sizes as well. I just thought I would check as currently if you have to have the fallback as a small image, it will be pixelated on browsers that don't support picture tags.

**Current Markup**

```
<picture>
    <img src="../images/image@3x.jpg" alt="example">
</picture>
```

**Current Result**

```
<picture>
    <source type="image/webp" srcset=" ../images/image@3x.webp 1750w">
    <source srcset="../images/image@3x.jpg 1750w">
    <img src="../images/image@3x.jpg" alt="example">
</picture>
```

**Ideal Result (with complete array and @3x fallback)**

```
<picture>
    <source type="image/webp" srcset="../images/image.webp 583w,
                    ../images/image@1,5x.webp 875w,
                    ../images/image@2x.webp 1167w,
                    ../images/image@3x.webp 1750w">
    <source srcset="../images/image.jpg 583w,
                    ../images/image@1,5x.jpg 875w,
                    ../images/image@2x.jpg 1167w,
                    ../images/image@3x.jpg 1750w">
    <img src="../images/image@3x.jpg" alt="example">
</picture>
```

**Comment by goiblas** [comment]
Thank you for your contribution, I have published an update with your proposal

**Comment by guyhamilton** [comment]
@goiblas - Thanks so much for the quick reply! That works perfectly - great work!!
