### ISSUE TITLE
ExperimentalWarning: The fs.promises API is experimental

### ISSUE THREAD

**Issue by guyhamilton** [goiblas/gulp-add-source-picture#2]
Hello again!
I just noticed when I run the gulp task I get the error "(node:9734) ExperimentalWarning: The fs.promises API is experimental" - I tracked this down to the exact line of code for adding the source:

`.pipe(addSource(processing.dist.img.processed))`

Any ideas if this is an issue or any way to get around the warning? Thanks!

**Comment by goiblas** [comment]
It´s a warning of previous node, in the stable version they have eliminated the experimental flag.

Is it possible that you update your node version to remove the warning?

You can see the node issues closed in [https://github.com/nodejs/node/pull/26581](https://github.com/nodejs/node/pull/26581)
