### ISSUE TITLE
Gutil not defined when trying to run

### ISSUE THREAD

**Issue by guyhamilton** [goiblas/gulp-add-source-picture#3]
Hi again, I'll preface this with I'm not sure whether this is a problem with gulp-add-source-picture or something else in my setup as i'm a bit of a noob (sorry)! But today when I tried to run gulp I got the below error. Commenting out the '.pipe(addSource(processing.dist.img.processed))' line got the task to run like normal again. If you have any ideas or can point me in the direction if it's something else to look into that would be great. Thanks again!

"UnhandledPromiseRejectionWarning: ReferenceError: gutil is not defined
    at Promise.all.then.catch.err (/Users/Guy/Dropbox/Sites/theme-twofold/node_modules/gulp-add-source-picture/index.js:108:24)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
(node:1251) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)"

**Comment by goiblas** [comment]
Throws an error in the process but the error library is deprecated (gutil), I will update it so we will able to see the error and fix it. I don't think it's a problem with your setup.

Thanks for the feedback.

**Comment by guyhamilton** [comment]
@goiblas - Ahh thanks very much! Glad to hear its not me! Guy.

**Comment by guyhamilton** [comment]
Perfect, I updated that and that error is gone, however now I'm getting the following TypeError in plugin "gulp-add-source-picture" while running the addSource task  - any ideas?
 
'Message:
    Path must be a string. Received undefined
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false'

**Comment by goiblas** [comment]
Maybe some image is giving error, but I don't know, can I have a look at the project?

**Comment by guyhamilton** [comment]
Ahh thank you. I went through all my HTML files and tracked it down to an image tag that had been commented out which caused the error. Once I removed the comments it processed the file. Hope that helps!
