### ISSUE TITLE
Provision to add sizes for code validation

### ISSUE THREAD

**Issue by guyhamilton** [goiblas/gulp-add-source-picture#5]
Hello again! I just went to validate my project and I get the error: "Error: When the srcset attribute has any image candidate string with a width descriptor, the sizes attribute must also be present".

Could you add provision to add the sizes? Potentially just something like the below for now which will make it validate.

`sizes="100vw"`

Down the track it would be great to be able to set a number of different size sets and apply those to the images depending on the class on the image or something similar.

**Comment by goiblas** [comment]
Thank you for your contribution
